apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - ../../base/foobar
patches:
  - path: ingressroute.yaml
  - path: deployment.yaml
  # - path: certificate.yaml
