apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik-system
resources:
  - helmrelease.yaml
  - namespace.yaml
  - middleware/redirect-scheme.yaml
configurations:
  - kustomizeconfig.yaml
