---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik
  namespace: traefik-system
spec:
  dnsNames:
    - "*.cloud.local"
    - "cloud.local"
  issuerRef:
    kind: ClusterIssuer
    name: self-signed
  secretName: traefik-crt
