apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik-system
configMapGenerator:
  - files:
      - values.yaml=values.yaml
    name: traefik-values
resources:
  - ../../base/traefik-proxy
  - certificate.yaml
patches:
  - path: helmrelease.yaml
