---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/traefik/traefik-helm-chart/raw/v36.0.0/traefik/crds/traefik.io_ingressroutes.yaml
  - https://github.com/traefik/traefik-helm-chart/raw/v36.0.0/traefik/crds/traefik.io_ingressroutetcps.yaml
  - https://github.com/traefik/traefik-helm-chart/raw/v36.0.0/traefik/crds/traefik.io_ingressrouteudps.yaml
  - https://github.com/traefik/traefik-helm-chart/raw/v36.0.0/traefik/crds/traefik.io_middlewares.yaml
  - https://github.com/traefik/traefik-helm-chart/raw/v36.0.0/traefik/crds/traefik.io_middlewaretcps.yaml
  - https://github.com/traefik/traefik-helm-chart/raw/v36.0.0/traefik/crds/traefik.io_serverstransports.yaml
  - https://github.com/traefik/traefik-helm-chart/raw/v36.0.0/traefik/crds/traefik.io_serverstransporttcps.yaml
  - https://github.com/traefik/traefik-helm-chart/raw/v36.0.0/traefik/crds/traefik.io_tlsoptions.yaml
  - https://github.com/traefik/traefik-helm-chart/raw/v36.0.0/traefik/crds/traefik.io_tlsstores.yaml
  - https://github.com/traefik/traefik-helm-chart/raw/v36.0.0/traefik/crds/traefik.io_traefikservices.yaml
